  update-manifest:
    needs: build-scan-push

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Platform Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.PLATFORM_REPO }}
          token: ${{ secrets.PLATFORM_REPO_TOKEN }}
          path: platform-repo

      - name: Update Image Tag
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i "s|image: .*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ACCOUNTS_ECR_REPOSITORY:$IMAGE_TAG|g" \
          platform-repo/applications/accounts-service/deployment.yaml

      - name: Commit Changes
        run: |
          cd platform-repo

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git diff --staged --quiet || \
          git commit -m "Deploy accounts-service image ${{ github.sha }}"

      - name: Push Changes
        run: |
          cd platform-repo
          git push