name: Accounts CI

on:
  push:
    branches:
      - main
    paths:
      - 'accounts-service/**'
      - '.github/workflows/accounts-ci.yaml'

permissions:
  id-token: write
  contents: read

concurrency:
  group: accounts-ci
  cancel-in-progress: true

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
  ECR_REPOSITORY: ${{ vars.ACCOUNTS_ECR_REPOSITORY }}

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t $ECR_REPOSITORY:${{ github.sha }} \
            ./accounts-service

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Tag Image
        run: |
          docker tag \
            $ECR_REPOSITORY:${{ github.sha }} \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

      - name: Push Image
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}
